### ISSUE TITLE
Given block height does not match current blockchain height

### ISSUE THREAD

**Issue by viktorsaenko** [PoC-Consortium/scavenger#60]
I've got that error from a few servers after upgrading to 1.7.6 version. I hadn't got that error with previous scavenger versions.
Last value:  message: {"result":"Given block height does not match current blockchain height","requestProcessingTime":0}

**Comment by JohnnyFFM** [comment]
Hi, this error is nothing to worry about and yes, there should be more of these since 1.7.x. Basically there is a delay between block discovery in the wallet and block propagation to scavenger. You can reduce this delay by lowering the "get_mining_info_interval" parameter in config.yaml. default is 3000, but 1000 should help avoiding some of these error messages. The chance of seeing this error message is also linked to scantime (the longer your scantime the more likely you'll see this message) and to dual-chain-mining.

**Comment by viktorsaenko** [comment]
Hi. Thanks! I will try to change it.
