### ISSUE TITLE
Questions regarding this project.

### ISSUE THREAD

**Issue by Joe23232** [PoC-Consortium/scavenger#86]
Hi, I have some questions regarding this project:

1. Am I able to import it as a library/crate into my own Rust code and integrate it into my own software so I can compile all into a single executable?
2. Does it support either [Beam](https://beam.mw/),  [Zcash](https://z.cash/) or [Monera](https://www.getmonero.org/) or any other privacy respecting cryptocurrency?
3. How efficient is it compared to something like [gminer](https://github.com/develsoftware/GMinerRelease)?
4. Do you guys get a commission from my cryptomining if I were to use this library/crate?

**Comment by boner-cmd** [comment]
If you had done any investigation, you would know that this is a Proof of Space mining program. All of the other algorithms you mentioned are Proof of Work. Since you have posted this exact question to nearly 30 other crypto repos, most with equally little independent research and investigation, I have reported your account for spam. Next time, before you post an issue, at least know what program you are posting an issue for.
