### ISSUE TITLE
Block mix-ups / block chaos with subsequent timeout?

### ISSUE THREAD

**Issue by McCalm** [PoC-Consortium/scavenger#95]
Version: v.1.8.0
OS: Windows 10.

Hello,

Hello, by chance I discovered this constellation today that brought the miner to a standstill. Block 886331 was created before block 886330. There was also no end of the round (round finished).

![grafik](https://user-images.githubusercontent.com/78034375/119383725-fdf0e680-bcc3-11eb-8ade-f03c78f87fde.png)

The background is probably an attempted fork with block 886330.

![grafik](https://user-images.githubusercontent.com/78034375/119384252-b1f27180-bcc4-11eb-887c-d6d28b656f4a.png)

The miner did not continue his work until many minutes later. 

![grafik](https://user-images.githubusercontent.com/78034375/119384540-23322480-bcc5-11eb-99de-9d62a1ee7590.png)

Now all "new" sent DL's are to late:

![grafik](https://user-images.githubusercontent.com/78034375/119384868-99cf2200-bcc5-11eb-9aae-d9653a0ce776.png)

Back to "normal" work.

See also screenshots,
with regards,
McCalm

**Comment by JohnnyFFM** [comment]
Superinteresting case. And I think Scavenger worked excellent in this situation. 

When it comes to forks, Scav is is well prepared. It starts mining based on a gensig change, not height change. That's why block height can go down. And yes, your wallet was stuck on a fork. And I really wonder why it took the wallet so long to resolve the fork (the long pause), no new block on the fork. Maybe not enough connections or too many nodes on the fork. Once resolved, the wallet was updating quickly to the latest block. During these updates, the wallet spams new blocks to scavenger and scavenger is always to late to respond. This also happens when you mine while syncing -> normal behaviour. 

So if you want to look further into this, you would need to investigate why your wallet took so long to resolve the fork. 

Johnny

**Comment by McCalm** [comment]
Exactly, it's just about the break of over 20 minutes. As a rule, there should be no processing delay here. If there are connection problems, Scavenger would have to document this accordingly and also display it as a "problem". In my opinion, there is a working error in the program according to manage the order in which the individual information was transmitted via the socket. With peer-to-peer connections in particular, it is important to check when the individual packets were received (timestamp). I already noticed this when Scavenger still sends another share after the end of the round. But fine, if it's not a problem, everything's fine.
Thank you,
regards,
McCalm

**Comment by JohnnyFFM** [comment]
Well, there was no connection problem between wallet and scav. scav would report errors if the connection to the wallet is down.

It means scav says: hi wallet new block? wallet says no. Scavs asks every 3s. but wallet always said "no new block" for over 20min in your case. So the issue was with the wallet and not with scavenger. every other miner would have shown the same. 

Regarding the shares send after end of the round: This is also different: Scavengers sent the share before the end.. but the answer was received after the end. and scav only prints a line after the answer. So this is due to latency.

**Comment by McCalm** [comment]
Thank you for your help.

After watching the Node for some time, I also came to the conclusion that the "old" Node here was probably not running synchronously from time to time and this naturally affected the miner, too. 

So I tackled this construction site and optimized the node with the appropriate hardware environment.
OK, great, thanks again!

Oh yes, what I would like really like to see as a further function in the miner: A parameter that allows the plot directories to be automatically rescanned. At the moment you have to quit the miner and restart it when additional new plots have been added. 

This is just a suggestion.
Greetings, McCalm

**Comment by JohnnyFFM** [comment]
rescan not planned, latest version has some more fixes to handle the frequent forks of burst.
